name: JavaScript Test

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js '11.x'
      uses: actions/setup-node@v1
      with:
        node-version: '11.x'
    - name: Clean install dependencies
      run: npm ci
      working-directory: ./js
    - name: Test by jest
      run: npm test
      working-directory: ./js