name: Python Test

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
      working-directory: ./python
    - name: Install dependencies
      run: pipenv sync --dev
      working-directory: ./python
    - name: Test by pytest
      run: pipenv run test
      working-directory: ./python